name: starline_engine_hours
description: Вычисление моточасов с помощью API StarLine Телематика
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  http: ^0.13.4
  json_serializable: ^6.1.3
  faker: ^2.0.0
  shared_preferences: ^2.0.11
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0 
  auto_size_text: ^3.0.0
  flutter_native_splash: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/car-engine.png"

flutter:
  uses-material-design: true
  assets:
    - assets/car-engine.png
